GET http://localhost:5000/trade

###
GET http://localhost:3000/

###

POST http://localhost:3000/schedulesUpdate/
Content-Type: application/json

{
    "name":"Mike",
    "adminRegister1": "string", 
    "adminDate": 1591233223453
}
 

