const mongoose = require("mongoose");
const employeeModel = require("../models/employeeSchema");

mongoose.connect(
  process.env.MONGODB_URI || "mongodb://localhost:27017/Workeasy"
);

const employeeData = [
  {
    employerName: "Company",
    firstname: "Alan",
    middlename: "",
    lastname: "Jackman",
    dob: "1990-01-20",
    ssn: "7534267598",
    email: "email@email.com",
    address1: "123 Main St",
    address2: "",
    city: "New York",
    state: "NY",
    zipcode: "11101",
    password: "",
    password2: "",
    accessType: "employee",
    employers: [
      {
        employer: "The Shop",
        jobDescription: "A description of a company",
        startDate: "2015-03-20",
        endDate: "2019-03-20",
        mgrName: "Travis",
        mgrPhone: "5625895632",
        leaveReason: "to work here",
        currentlyEmployed: false,
      },
    ],
    employeeStatus: "recruit",
    errors: {},
    accessType: "employee",
  },
  {
    employerName: "Company",
    firstname: "Irma",
    middlename: "",
    lastname: "Benson",
    dob: "1990-01-20",
    ssn: "7534267598",
    email: "email@email.com",
    address1: "123 Main St",
    address2: "",
    city: "New York",
    state: "NY",
    zipcode: "11101",
    password: "",
    password2: "",
    accessType: "employee",
    employers: [
      {
        employer: "The Shop",
        jobDescription: "A description of a company",
        startDate: "2015-03-20",
        endDate: "2019-03-20",
        mgrName: "Travis",
        mgrPhone: "5625895632",
        leaveReason: "to work here",
        currentlyEmployed: false,
      },
    ],
    employeeStatus: "recruit",
    errors: {},
    accessType: "employee",
  },
  {
    employerName: "Company",
    firstname: "Dana",
    middlename: "",
    lastname: "Trevor",
    dob: "1990-01-20",
    ssn: "7534267598",
    email: "email@email.com",
    address1: "123 Main St",
    address2: "",
    city: "New York",
    state: "NY",
    zipcode: "11101",
    password: "",
    password2: "",
    accessType: "employee",
    employers: [
      {
        employer: "The Shop",
        jobDescription: "A description of a company",
        startDate: "2015-03-20",
        endDate: "2019-03-20",
        mgrName: "Travis",
        mgrPhone: "5625895632",
        leaveReason: "to work here",
        currentlyEmployed: false,
      },
    ],
    employeeStatus: "recruit",
    errors: {},
    accessType: "employee",
  },
  {
    employerName: "Company",
    firstname: "John",
    middlename: "",
    lastname: "Osborne",
    dob: "1990-01-20",
    ssn: "7534267598",
    email: "email@email.com",
    address1: "123 Main St",
    address2: "",
    city: "New York",
    state: "NY",
    zipcode: "11101",
    password: "",
    password2: "",
    accessType: "employee",
    employers: [
      {
        employer: "The Shop",
        jobDescription: "A description of a company",
        startDate: "2015-03-20",
        endDate: "2019-03-20",
        mgrName: "Travis",
        mgrPhone: "5625895632",
        leaveReason: "to work here",
        currentlyEmployed: false,
      },
    ],
    employeeStatus: "recruit",
    errors: {},
    accessType: "employee",
  },
  {
    employerName: "Company",
    firstname: "Michael",
    middlename: "",
    lastname: "McDonald",
    dob: "1990-01-20",
    ssn: "7534267598",
    email: "email@email.com",
    address1: "123 Main St",
    address2: "",
    city: "New York",
    state: "NY",
    zipcode: "11101",
    password: "",
    password2: "",
    accessType: "employee",
    employers: [
      {
        employer: "The Shop",
        jobDescription: "A description of a company",
        startDate: "2015-03-20",
        endDate: "2019-03-20",
        mgrName: "Travis",
        mgrPhone: "5625895632",
        leaveReason: "to work here",
        currentlyEmployed: false,
      },
    ],
    employeeStatus: "recruit",
    errors: {},
    accessType: "employee",
  },
  {
    employerName: "Company",
    firstname: "Parker",
    middlename: "",
    lastname: "Davis",
    dob: "1990-01-20",
    ssn: "7534267598",
    email: "parker@email.com",
    address1: "123 Main St",
    address2: "",
    city: "New York",
    state: "NY",
    zipcode: "11101",
    password: "",
    password2: "",
    accessType: "employee",
    employers: [
      {
        employer: "The Shop",
        jobDescription: "A description of a company",
        startDate: "2015-03-20",
        endDate: "2019-03-20",
        mgrName: "Travis",
        mgrPhone: "5625895632",
        leaveReason: "to work here",
        currentlyEmployed: false,
      },
    ],
    employeeStatus: "recruit",
    errors: {},
    accessType: "employee",
  },
  {
    employerName: "Company",
    firstname: "Janet",
    middlename: "",
    lastname: "Anderson",
    dob: "1990-01-20",
    ssn: "7534267598",
    email: "janet@email.com",
    address1: "123 Main St",
    address2: "",
    city: "New York",
    state: "NY",
    zipcode: "11101",
    password: "",
    password2: "",
    accessType: "employee",
    employers: [
      {
        employer: "The Shop",
        jobDescription: "A description of a company",
        startDate: "2015-03-20",
        endDate: "2019-03-20",
        mgrName: "Travis",
        mgrPhone: "5625895632",
        leaveReason: "to work here",
        currentlyEmployed: false,
      },
    ],
    employeeStatus: "recruit",
    errors: {},
    accessType: "employee",
  },
];
module.exports = employeeData;
